//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int IDSale { get; set; }
        public Nullable<int> IDDrug { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> IDEmployee { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
